name: test11
description: dfghjkl
keywords:
  - websocket
  - network
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD
logo: https://www.lua.org/images/lua-logo.gif

source_file:
  - src/*.c
  - src/*.S

build_config:
  include:
    - include
  cflag: "test zm"                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
