name: test11
description: dfghjkl
keywords:
  - websocket
  - network
license: MIT                                   # GPLv2，LGPLv2.1，MIT，Apache license v2.0，BSD
logo: http://img1.imgtn.bdimg.com/it/u=4289609089,1236661732&fm=26&gp=0.jpg

source_file:
  - src/*.c
  - src/*.S

build_config:
  include:
    - include
  cflag: ""                             # C 编译器所需要要的编译参数
  define:                                      # 宏定义
    - CONFIG_USING_TLS

install:
  - dest: include
    source:
      - "include/librws.h"
